apiVersion: v1
kind: Pod
metadata:
  name: surrealrecepti
spec:
  containers:
    - name: surrealdb
      image: "docker.io/surrealdb/surrealdb:latest"
      args:
      - "start"
      - "--log"
      - "trace"
      - "--auth"
      - "--user"
      - "root"
      - "--pass"
      - "root"
      - "file:/db/reipeDump.db"
      volumeMounts:
        - mountPath: /db:Z
          name: surreal_data
          readOnly: false
      ports:
        - containerPort: 8000
          protocol: TCP
          hostPort: 8000
        - containerPort: 8000
          protocol: UDP
          hostPort: 8000

      # user: root

      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

  volumes:
    - name: surreal_data
      hostPath:
        path: "./volume"
    
  restartPolicy: Always